ARCHIVE_CONTENTS = "build.sbt project src target run.sh"

archive_task1_complete:
	tar xvf task1-complete.tar $(ARCHIVE_CONTENTS)

archive_task2_complete:
	tar xvf task2-complete.tar $(ARCHIVE_CONTENTS)

archive_task3_complete:
	tar xvf task2-complete.tar $(ARCHIVE_CONTENTS)

create_submission:
	tar xvf Submission.tar task*.tar
