CXX = gcc
CPP = g++

all: reverse_string atoi_impl ternary_conditional prbs7 selection_sort

reverse_string:
	$(CXX) ./reverse_string.c -o ./reverse_string

atoi_impl:
	$(CXX) ./atoi_impl.c -o ./atoi_impl

ternary_conditional:
	$(CXX) ./ternary_conditional.c -o ./ternary_conditional

prbs7:
	$(CXX) ./prbs7.c -o ./prbs7

clean:
	rm ./reverse_string ./atoi_impl ./ternary_conditional ./prbs7 ./selection_sort

selection_sort:
	$(CPP) -g3 ./selection_sort.cpp -o ./selection_sort
