[package]
name = "city-pop"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

[[bin]]
name = "city-pop"

[dependencies]
csv = "1.1"
flate2 = "1.0"
serde = {version = "1.0", features=["derive"]}
structopt = "0.3"
anyhow = "1.0"