[package]
name = "city-pop"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]

[[bin]]
name = "city-pop"

[dependencies]
csv = "0.*"
rustc-serialize = "0.*"
getopts = "0.*"
flate2 = "0.*"
