SCALAC = scalac

SCALA_FILES = HelloWorld Test0 Test10 Test11 Test12 Test13 Test14 Test15 Test16 Test17 Test1 Test2 Test3 Test4 Test5 Test6 Test7 Test8 Test9 Test 

%: %.scala
	$(SCALAC) $*.scala

all: $(SCALA_FILES)

clean:
	rm *.class
