[package]
name = "one_time_pad"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]

[dependencies]
rayon = "0.8"
rand = "*"
pyo3 = "0.2"

[lib]
name = "one_time_pad"
crate-type = ["cdylib"]
