[package]
name = "one_time_pad"
version = "0.1.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]

[dependencies]
rayon = "0.8"
rand = "*"

[lib]
name = "one_time_pad"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "*"
default-features = false
# features = ["extension-module"]
